name: TA-WebEngineering
services:
  load-balancer:
    image: nginx:alpine
    container_name: load-balancer
    restart: always
    ports:
      - "8888:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minitwitter1
      - minitwitter2

  postgres:
    image: postgres:16-alpine
    container_name: webengineering
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 10

  # API 1 (npm / Port 3300)
  minitwitter1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minitwitter1
    restart: always
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@webengineering:5432/${POSTGRES_DB}
      command: /bin/sh -c "npx drizzle-kit push && node server.js"
      NODE_ENV: production
      PORT: 3300
    depends_on:
      postgres:
        condition: service_healthy

  minitwitter2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minitwitter2
    restart: always
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@webengineering:5432/${POSTGRES_DB}
      command: /bin/sh -c "npx drizzle-kit push && node server.js"
      NODE_ENV: production
      PORT: 3300
    depends_on:
      postgres:
        condition: service_healthy